services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      # Set the appropriate timezone for your location
      TZ: ${TZ}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: ${FTLCONF_dns_listeningMode}
    # Volumes store your data between container upgrades  
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      - ./dnsmasq.d/:/etc/dnsmasq.d/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https://${TRAEFIK_DOMAIN}/?$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=https://${TRAEFIK_DOMAIN}/admin"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.permanent=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    cap_add:
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped

networks:
  traefik:
    external: true
